apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lightspeed-test-02
  namespace: openshift-gitops
  labels:
    type: benchmark
spec:
  destination:
    name: in-cluster
    namespace: default
  project: default
  source:
    path: lightspeed-benchmark/test-02
    repoURL: https://github.com/joelapatatechaude/ols-test
    targetRevision: main

