---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tictactoe-vol
  namespace: ols-test-06
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi

